import React, { useCallback, useState } from 'react';
import {
  View,
  Text,
  FlatList,
  StyleSheet,
  RefreshControl,
  TouchableOpacity,
} from 'react-native';
import { useNavigation } from '@react-navigation/native';
import { Receipt, ChevronRight } from 'lucide-react-native';
import { useAuth } from '../context/AuthContext';
import { apiFetch } from '../services/api';
import { Screen, ScreenHeader, AppCard, EmptyState } from '../components/ui';
import { InvoiceExportPanel } from '../components/InvoiceExportPanel';
import type { ExportInvoice } from '../utils/invoiceExport';
import { colors, radii, space, typography, TAB_BAR_CONTENT_INSET } from '../theme/tokens';

type Inv = ExportInvoice & {
  id: number;
};

function paymentStatusLabel(inv: Inv): string | null {
  const balance = Number(inv.balance_amount) || 0;
  if (balance > 0) {
    return 'Pending payment';
  }
  return null;
}

export default function InvoicesScreen() {
  const { token, user } = useAuth();
  const navigation = useNavigation();
  const [items, setItems] = useState<Inv[]>([]);
  const [refreshing, setRefreshing] = useState(false);

  const load = useCallback(async () => {
    if (!token || !user?.company_id) {
      return;
    }
    const res = await apiFetch<{ status: boolean; data?: Inv[] }>('invoice/get_all_invoice.php', {
      body: { company_id: user.company_id },
      token,
    });
    if (res.status && res.data) {
      setItems(res.data);
    }
  }, [token, user?.company_id]);

  React.useEffect(() => {
    load();
  }, [load]);

  const ListHeader = () => (
    <View style={{ marginBottom: space.md }}>
      <InvoiceExportPanel invoices={items} />
    </View>
  );

  return (
    <Screen edges={['top', 'left', 'right']}>
      <ScreenHeader title="Invoices" subtitle="History, export, and totals" />
      <FlatList
        data={items}
        keyExtractor={(i) => String(i.id)}
        ListHeaderComponent={ListHeader}
        refreshControl={
          <RefreshControl
            refreshing={refreshing}
            onRefresh={async () => {
              setRefreshing(true);
              await load();
              setRefreshing(false);
            }}
          />
        }
        contentContainerStyle={{ paddingHorizontal: space.xl, paddingBottom: TAB_BAR_CONTENT_INSET + 16 }}
        renderItem={({ item }) => {
          const pending = paymentStatusLabel(item);
          return (
            <TouchableOpacity
              activeOpacity={0.88}
              onPress={() => {
                const parent = navigation.getParent();
                if (parent) {
                  (
                    parent as { navigate: (n: string, p: { invoice_no: string }) => void }
                  ).navigate('InvoiceDetail', { invoice_no: item.invoice_no });
                }
              }}
            >
              <AppCard style={styles.card}>
                <View style={styles.top}>
                  <View style={styles.badge}>
                    <Receipt size={16} color={colors.primary} />
                    <Text style={styles.no}>{item.invoice_no}</Text>
                  </View>
                  <Text style={styles.amt}>₹{item.total_amount}</Text>
                </View>
                <Text style={styles.cust}>{item.customer_name}</Text>
                {item.cashier_name ? (
                  <Text style={styles.generatedBy}>Generated by: {item.cashier_name}</Text>
                ) : null}
                {pending ? (
                  <View style={styles.pendingBadge}>
                    <Text style={styles.pendingText}>{pending}</Text>
                    <Text style={styles.pendingMeta}>
                      Paid ₹{Number(item.paid_amount || 0).toFixed(2)} · Balance ₹
                      {Number(item.balance_amount || 0).toFixed(2)}
                    </Text>
                  </View>
                ) : null}
                <View style={styles.foot}>
                  <Text style={styles.date}>{item.created_at}</Text>
                  <ChevronRight size={18} color={colors.subtle} />
                </View>
              </AppCard>
            </TouchableOpacity>
          );
        }}
        ItemSeparatorComponent={() => <View style={{ height: space.md }} />}
        ListEmptyComponent={
          <EmptyState
            icon={Receipt}
            title="No invoices yet"
            description="Completed sales from billing will show up here."
          />
        }
      />
    </Screen>
  );
}

const styles = StyleSheet.create({
  card: { padding: space.lg },
  top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: colors.primarySoft,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: radii.pill,
  },
  no: { ...typography.caption, color: colors.primary, fontWeight: '800' },
  amt: { ...typography.h2, color: colors.primary },
  cust: { ...typography.body, fontWeight: '600', marginTop: 12 },
  generatedBy: { ...typography.caption, color: colors.muted, marginTop: 6 },
  pendingBadge: {
    marginTop: 10,
    padding: 10,
    borderRadius: radii.md,
    backgroundColor: colors.errorSoft,
  },
  pendingText: { ...typography.caption, color: colors.error, fontWeight: '800' },
  pendingMeta: { ...typography.micro, color: colors.error, marginTop: 4 },
  foot: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  date: { ...typography.micro, color: colors.muted },
});
