import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';

export type DateFilter = 'daily' | 'weekly' | 'monthly';
export type PaymentFilter = 'all' | 'cash' | 'upi' | 'card' | 'online' | 'credit';

export type ExportInvoice = {
  invoice_no: string;
  customer_name: string;
  customer_phone?: string;
  total_amount: string | number;
  paid_amount?: string | number;
  balance_amount?: string | number;
  payment_method?: string;
  payment_type?: string;
  payment_status?: string;
  created_at: string;
  cashier_name?: string;
};

function parseDate(value: string): Date {
  const d = new Date(value.replace(' ', 'T'));
  return Number.isNaN(d.getTime()) ? new Date(0) : d;
}

function startOfDay(d: Date): Date {
  const x = new Date(d);
  x.setHours(0, 0, 0, 0);
  return x;
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

export function filterInvoicesForExport(
  invoices: ExportInvoice[],
  dateFilter: DateFilter,
  paymentFilter: PaymentFilter
): ExportInvoice[] {
  const now = new Date();
  const todayStart = startOfDay(now);

  return invoices.filter((inv) => {
    const created = parseDate(inv.created_at);
    let inRange = true;
    if (dateFilter === 'daily') {
      inRange = created >= todayStart;
    } else if (dateFilter === 'weekly') {
      const weekAgo = new Date(todayStart);
      weekAgo.setDate(weekAgo.getDate() - 6);
      inRange = created >= weekAgo;
    } else {
      inRange = created.getMonth() === now.getMonth() && created.getFullYear() === now.getFullYear();
    }
    if (!inRange) return false;

    if (paymentFilter === 'all') return true;
    const method = String(inv.payment_method || inv.payment_type || '').toLowerCase();
    if (paymentFilter === 'card') {
      return method === 'card' || method === 'online';
    }
    return method === paymentFilter;
  });
}

function buildSpreadsheetXml(invoices: ExportInvoice[]): string {
  const headers = [
    'Invoice No',
    'Date',
    'Customer',
    'Phone',
    'Total',
    'Paid',
    'Balance',
    'Payment',
    'Status',
    'Generated By',
  ];

  const headerRow = headers
    .map((h) => `<Cell><Data ss:Type="String">${escapeXml(h)}</Data></Cell>`)
    .join('');

  const dataRows = invoices
    .map((inv) => {
      const cells = [
        inv.invoice_no,
        inv.created_at,
        inv.customer_name,
        inv.customer_phone || '',
        String(Number(inv.total_amount) || 0),
        String(Number(inv.paid_amount) || 0),
        String(Number(inv.balance_amount) || 0),
        inv.payment_method || inv.payment_type || '',
        inv.payment_status || '',
        inv.cashier_name || '—',
      ];
      return `<Row>${cells
        .map((c, i) => {
          const type = i >= 4 && i <= 6 ? 'Number' : 'String';
          return `<Cell><Data ss:Type="${type}">${escapeXml(c)}</Data></Cell>`;
        })
        .join('')}</Row>`;
    })
    .join('');

  return `<?xml version="1.0"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:o="urn:schemas-microsoft-com:office:office"
 xmlns:x="urn:schemas-microsoft-com:office:excel"
 xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">
<Worksheet ss:Name="Invoices">
<Table>
<Row>${headerRow}</Row>
${dataRows}
</Table>
</Worksheet>
</Workbook>`;
}

async function writeTempFile(content: string, fileName: string): Promise<string> {
  const dir = FileSystem.documentDirectory;
  if (!dir) {
    throw new Error('File storage is not available on this device.');
  }
  const uri = `${dir}${fileName}`;
  // UTF-8 is the default; avoid EncodingType (not on main expo-file-system export in v19)
  await FileSystem.writeAsStringAsync(uri, content);
  return uri;
}

export async function exportInvoicesToExcel(invoices: ExportInvoice[], fileLabel: string): Promise<void> {
  if (invoices.length === 0) {
    throw new Error('No invoices match the selected filters.');
  }

  const xml = buildSpreadsheetXml(invoices);
  const fileName = `invoices-${fileLabel}-${Date.now()}.xls`;
  const uri = await writeTempFile(xml, fileName);

  const canShare = await Sharing.isAvailableAsync();
  if (!canShare) {
    throw new Error('Sharing is not available on this device.');
  }
  await Sharing.shareAsync(uri, {
    mimeType: 'application/vnd.ms-excel',
    dialogTitle: 'Export invoices',
  });
}
